### PR TITLE
Fix LGTM alerts

### PR DESCRIPTION
**Pull request by lisaychuang**
Hi @jdetaeye, I've referenced [LGTM alert snapshot page](https://lgtm.com/projects/g/frePPLe/frepple/snapshot/0aeeedc5aa4608b1c2ab264365943ce582255825/files/freppledb/common/static/js/frepple.js?sort=name&dir=ASC&mode=heatmap&showExcluded=false#V3060) and fixed two categories of errors:
- Added `var` declaration to variables
- Added `;` semicolons to avoid automated semicolon insertion

Please review when you get a chance, thanks!

### CODE REVIEW

**Comment by lisaychuang** [comment]
Commit [bda01e0](https://github.com/frePPLe/frepple/pull/302/commits/bda01e0dd174e76b588f7a3d3dd39001f63148a9), see [LGTM alert snapshot](https://lgtm.com/projects/g/frePPLe/frepple/snapshot/0aeeedc5aa4608b1c2ab264365943ce582255825/files/freppledb/input/templates/input/path.html?sort=name&dir=ASC&mode=heatmap&showExcluded=false#x3896cb4d4cd5f743:1) for details:

- Added `var` declaration to variables
- Fix `typeof` error for `string`

**Comment by lisaychuang** [comment]
Commit [e5a7f8e](https://github.com/frePPLe/frepple/pull/302/commits/e5a7f8e363f7cf45914dc49720b3f8340fc6d87e), see [LGTM alert snapshot](https://lgtm.com/projects/g/frePPLe/frepple/alerts/?mode=list&severity=warning) for details:

- Changed multi-line strings from string concatenation `+` to ES6 template literals using backticks `

**Comment by lisaychuang** [comment]
Commit [f560ebc](https://github.com/frePPLe/frepple/pull/302/commits/f560ebc2061aac8975d404ef54014575779284f6), see [LGTM alert snapshot](https://lgtm.com/projects/g/frePPLe/frepple/snapshot/0aeeedc5aa4608b1c2ab264365943ce582255825/files/freppledb/common/static/js/d3.js?sort=name&dir=ASC&mode=heatmap&showExcluded=false#x9b9a93785d052365:1) for details:

- Move variable declaration to top of function scope before use in `if` statements

**Comment by jdetaeye** [comment]
The changes from  https://github.com/frePPLe/frepple/pull/302/commits/f560ebc2061aac8975d404ef54014575779284f6 are in a third-party library. I prefer not to modify it.

The changes from https://github.com/frePPLe/frepple/pull/302/commits/55c029eaedfa95be6f842d7a8824a5bc6bb001e6
will be included. We actually don't need the id of these elements anyway, so I'll just remove those.

The changes from https://github.com/frePPLe/frepple/pull/302/commits/bda01e0dd174e76b588f7a3d3dd39001f63148a9 will be included as you suggest, except for the one on line 71.

The LGTM changes will be reviewed one by one, but look good to me.

Much appreciate the input! Thanks.

**Comment by lisaychuang** [comment]
@jdetaeye that sounds great, thank you for taking the time to review my commits. I'm glad I could help contribute to frePPle! Thank you for all your hard work maintaining this library!

**Comment by jdetaeye** [comment]
Closing this one.  Too many false positives, and low priority to correct all this.

**Pull request closed without merging**
