### PR TITLE
Clean up "scratch" image in Dockerfile definitions

### PR DESCRIPTION
**Pull request by mdukat**
I don't see any reference to "scratch" image being used elsewhere. I was able to build docker images successfully without those image definitions, as they really aren't doing anything special.

### CODE REVIEW

**Comment by jdetaeye** [comment]
Rejecting this one.

"Scratch" is a special docker feature.  It is used in multi-stage builds to keep the size of the docker image small. 
See https://docs.docker.com/build/building/multi-stage/

**Comment by mdukat** [comment]
Here, I hope this visualization will help.

image

**Comment by jdetaeye** [comment]
Sorry, yes, you are right.  I closed this one too quickly.

I agree with you it's not used.

**Comment by jdetaeye** [comment]
The package image is actually referenced in our build scripts. 
So keeping the lines.
https://github.com/frePPLe/frepple/blob/0e218c046eac7258addc9ae25ba47334be9ad22e/contrib/docker/CMakeLists.txt#L14C5-L14C94

**Comment by mdukat** [comment]
> The package image is actually referenced in our build scripts.

I have hard time understanding the point of line you linked, as well as [this line](https://github.com/frePPLe/frepple/blob/dac74d3d3d7c1ef25e22364eb77e4aae28be0a49/contrib/docker/CMakeLists.txt#L40). Built image from stage "package" is not published anywhere, as far as I can see (I took a look at github workflows), and it's not extracted anywhere later in these cmake targets.

My only bet, is that it is done for manual debian package extraction when building local development container, since any reference to "package" image build has option `--output type=local,dest=.`? But then again, why not extract it directly from target image?

**Comment by jdetaeye** [comment]
> My only bet, is that it is done for manual debian package extraction when building local development container, since any reference to "package" image build has option `--output type=local,dest=.`? 

Exactly.

> But then again, why not extract it directly from target image?

There may be alternatives in recent docker versions, but in the past many alternatives required creating a container from the image.

**Comment by mdukat** [comment]
Alright, thank you for your time.

**Pull request merged**
